title: Più Europa 4.0
description: > # this means to ignore newlines until "baseurl:"
  Blog del gruppo +Europa4.0, gruppo tematico di +Europa dedicato a Formazione, Innovazione e Ricerca
permalink: ':title/'
baseurl: "/test" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: +Europa 4.0 # add your name
author-img: piueu40.jpg # add your photo
about-author: lorem ipsum 1 # add description
social-twitter: PiuEuropa4_0 # add your Twitter handle
social-facebook: PiuEuropa4.0 # add your Facebook handle
social-github: piueuropa40 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: mercatanti4.0@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
